--DROP TABLE PigeonParcels
--DROP TABLE WarehouseParcels
--DROP TABLE Warehouses
--DROP TABLE Addresses
--DROP TABLE Parcels
--DROP TABLE ParcelTypes
--DROP TABLE Users
--DROP TABLE __EFMigrationsHistory